### ISSUE TITLE
DataServer still doesnt close socket properly

### ISSUE THREAD

**Issue by GoogleCodeExporter** [keyboardsurfer/blinkendroid#37]
```
DataServer does not shut down correctly.

When I simply started, stopped and started a server again using the SwingUI the 
following exception is thrown:

java.net.BindException: Address already in use
	at java.net.PlainSocketImpl.socketBind(Native Method)
	at java.net.PlainSocketImpl.bind(PlainSocketImpl.java:365)
	at java.net.ServerSocket.bind(ServerSocket.java:319)
	at java.net.ServerSocket.<init>(ServerSocket.java:185)
	at java.net.ServerSocket.<init>(ServerSocket.java:97)
	at org.cbase.blinkendroid.network.tcp.DataServer.run(DataServer.java:32)

It seems because the ServerSocket never gets closed, the thread is just 
interruped in the shutdown() method.

I propose calling ServerSocket.close() as well.
```

-----
Original issue reported on code.google.com by `das.dima...@googlemail.com` on 31 Oct 2010 at 10:54

**Comment by GoogleCodeExporter** [comment]
```
happens when server is stopped/killed/crashed while 
BlinkendroidDataServerProtocol has still an open socket to a client.... 
shutdown is not called
```

-----
Original comment by `lischke@gmail.com` on 2 Nov 2010 at 1:03

**Comment by GoogleCodeExporter** [comment]
```
closed socket.... shutdown is still not called cause of final fork
```

-----
Original comment by `lischke@gmail.com` on 2 Nov 2010 at 2:49
* Changed state: **Fixed**
